Complete Multi-Component prototype.
Added mc_del to DAL implementation plus minor fixes throughout MC DAL.
Updated build proecess to build and link nelib from erasureUtils.
Added script to build a directory tree simulating a multi-component repo.

diff --git a/fuse/scripts/build_marfs b/fuse/scripts/build_marfs
--- a/fuse/scripts/build_marfs
+++ b/fuse/scripts/build_marfs
@@ -154,6 +154,15 @@ fi
 
 echo
 echo "### ................................................................."
+echo "### making libne"
+echo "### ( cd $LIBNE && make clean && make libne.a CC=$COMPILER )"
+if !( cd $LIBNE && make clean && make libne.a CC=$COMPILER ); then
+    echo "couldn't build libne"
+    exit 1
+fi
+
+echo
+echo "### ................................................................."
 echo "### making libmarfs"
 echo "### ( cd $FUSE && make clean && make $FUSE_ARGS )"
 if !( cd $FUSE && make clean && make $FUSE_ARGS CC=$COMPILER ); then
