Improvements in handling MarFS xattrs, plus a demo program.
The little program demo_read_write_xattrs2.c shows two approaches to
reading/modifying/writing MarFS system xattrs on some file.  this might
help people who are starting to write test code, to understand how to do
it.  Comments in the code explain the finer points.

This code helped me debug some of the xattr stuff for fuse.  Fuse itself is
still a work-in-progress, here.  Just checking in to support
demo_read_write_xattrs2.c

diff --git a/fuse/src/Makefile b/fuse/src/Makefile
--- a/fuse/src/Makefile
+++ b/fuse/src/Makefile
@@ -1,29 +1,65 @@
 all: marfs_fuse
 
-GIT = ~/projects/marfs/git
+
+GIT = `readlink -f ~/projects/marfs/git`
+SYS = `readlink -f ~/projects/marfs/filesys`
 
 OBJS = marfs_base.o common.o
+H    = marfs_base.h common.h
 
 # MNT  = ./filesys/mnt
-MNT  = $(GIT)/fuse/filesys/mnt
+MNT  = $(SYS)/mnt
+MDFS = $(SYS)/mdfs/test00
+
+
+
+
+# if you set the environment variable DEBUG, we'll add '-g', and defined
+# DEBUG for the pre-processor.
+ifeq ($(DEBUG),1)
+	CFLAGS += -g
+	DEFS   += DEBUG=1
+else ifeq ($(DEBUG),2)
+	CFLAGS += -ggdb -save-temps
+	DEFS   += DEBUG=1
+else ifeq ($(DEBUG),3)
+	CFLAGS += -pg
+	DEFS   += DEBUG=2
+else
+	CFLAGS += -O3
+	DEFS   += DEBUG=0
+endif
+
+
+### LIBAWS4C = /users/jti/projects/ecs_hobo/tools/aws4c
+LIBAWS4C = `readlink -f ~/projects/ecs_hobo/tools/aws4c`
+
 
 # c99 needed for gcc 4.4.7 to know snprintf(), and floorf()
-CFLAGS += -Wall -std=c99 `pkg-config fuse --cflags`
-# CFLAGS += -Wall
+CFLAGS += -Wall -std=c99 `pkg-config fuse --cflags` -I $(LIBAWS4C) -I.
+CFLAGS += $(patsubst %, -D%, $(DEFS))
 
-LDFLAGS += `pkg-config fuse --cflags --libs` -lm
+
+LDFLAGS += `pkg-config fuse --cflags --libs` -lm -L $(LIBAWS4C) -laws4c
+
+
 
 
 # ...........................................................................
-# back and forth to HB's test node with XFS (supporting xattrs) at 10.135.0.2
+# back and forth to test node
+#
+# [see ./init_test_node, to initialize a test node with everything I need]
 
-# only works from ccstargate
-2hb:
-	rsync -Pvaurl ~/projects/marfs/git/fuse/src/ root@10.135.0.2:/root/projects/marfs/git/fuse/src
+# WORK = 10.135.0.2
+WORK = 10.146.0.3
 
-# only works from ccstargate
-fromhb:
-	rsync -Pvaurl root@10.135.0.2:/root/projects/marfs/git/fuse/src/ ~/projects/marfs/git/fuse/src
+# only works on ccstargate, or cc-gate
+2work:
+	rsync -Pvaurl ~/projects/marfs/git/fuse/src/ root@$(WORK):/root/projects/marfs/git/fuse/src
+
+# only works on ccstargate, or cc-gate
+fromwork:
+	rsync -Pvaurl root@$(WORK):/root/projects/marfs/git/fuse/src/ ~/projects/marfs/git/fuse/src
 
 # ...........................................................................
 
@@ -31,8 +67,12 @@ fromhb:
 
 
 # currently a simple top-level FUSE daemon
-marfs_fuse: $(OBJS) marfs_fuse.c
+marfs_fuse: $(OBJS) marfs_fuse.c $(OBJS)
 	gcc $(CFLAGS) -o marfs_fuse $(LDFLAGS) $(OBJS) marfs_fuse.c
+
+# aplications that link with various marfs support libs
+demo_%: demo_%.o $(OBJS)
+	gcc -o $@ $< $(LDFLAGS) $(OBJS)
 
 
 
@@ -48,14 +88,19 @@ mntlog: marfs_fuse
 	@ echo
 	@ echo "mounting at $(MNT)"
 	marfs_fuse -f $(MNT) > foo.log 2>&1 &
+	#
+	# TBD: while (! `mount | grep fuse | grep -v fusectl | wc -l`) ; do (echo sleeping; sleep 1) done
+	@ echo "sleeping to give background fuse a chance to start"
+	sleep 1
 
 # TBD should succeed silently if not mounted
 umnt:
-	fusermount -u $(MNT)
+	fusermount -u $(MNT) || echo "already unmounted"
 
 
+# wipe all state from MDFS and object-store
 reset:
-	rm -f /mnt/xfs/jti/filesys/mdfs/test00/foo
+	rm -f $(MDFS)/foo
 
 
 # TBD: develop a unit-test script to run ops on the mount-point
@@ -67,16 +112,18 @@ reset:
 # 	unit $(MNT)
 # 	$(MAKE) umount
 
-# test: umnt clean marfs_fuse reset mntlog
-test: clean marfs_fuse reset mntlog
-	echo foo > ../filesys/mnt/test00/foo
-
+# after edits: unmount, rebuild (if needed), wipe MDFS, mount, run test, show the log
+redo: umnt marfs_fuse reset mntlog
+	echo "foo" > $(MNT)/test00/foo || echo "failed"
+	tail foo.log
+	@ echo
+	$(MAKE) mdfs-foo
 
 
 %: %.o
 	gcc -o $@ $< $(LDFLAGS)
 
-%.o: %.c
+%.o: %.c %.h
 	gcc $(CFLAGS) -c -o $@ $<
 
 
@@ -97,6 +144,11 @@ clean:
 	$(RM) core.*
 
 
+# show quick diagnostics of the guts of an MDFS file
+#  e.g. 'make mdfs-foo' shows ...filesys/mdfs/test00/foo
+mdfs-%:
+	@ ls -l   $(MDFS)/$*
+	@ attr -l $(MDFS)/$*
 
 
 # -- various testing
@@ -119,4 +171,8 @@ loc:
 show_inc_path:
 	gcc -Wp,-v $(CFLAGS) -c -o marfs_base.o marfs_base.c
 
+show_cflags:
+	@ echo "CFLAGS = $(CFLAGS)"
 
+show_env:
+	printenv
